### ISSUE TITLE
Offline pruning fails when state sync enabled

### ISSUE THREAD

**Issue by cryptoklings** [ava-labs/avalanchego#1539]
**Describe the bug**
Discussion with team member [here](https://discord.com/channels/578992315641626624/620633143002660874/1109941690455838781). See _dub_rado_'s replies a few messages down.

**To Reproduce**
Start the node (avalanchego v.1.10.1) with config as such:
```
{
  "offline-pruning-enabled": true,
  "offline-pruning-data-directory": "/opt/avalanchego/offline-pruning",
  "state-sync-enabled": true
}
```

**Expected behavior**
It should start pruning.

**Screenshots**
N/A

**Logs**
Gives the following error, then gracefully restarts only to end up in exactly the same error.
```
May 22 19:56:17 avalanche-mainnet-vm avalanchego[142903]: INFO [05-22|19:56:17.281] <C Chain> github.com/ava-labs/coreth/eth/backend.go:441: Starting offline pruning dataDir=/opt/avalanchego/offline-pruning bloomFilterSize=512

May 22 19:56:17 avalanche-mainnet-vm avalanchego[142903]: [05-22|19:56:17.282] FATAL chains/manager.go:338 error creating required chain {"subnetID": "11111111111111111111111111111111LpoYY", "chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "vmID": "mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6", "error": "error while creating new snowman vm failed to create new pruner with data directory: /opt/avalanchego/offline-pruning, size: 512, due to: failed to create snapshot for pruning, must restart without offline pruning disabled to recover: block hash stored on disk (0x1dc661d04aeca7b4eac83275be71ce2fe87928f998d033b2ac9bcf2b751b1410) does not match last accepted (0xfbc771f139b99731897acc572e4813a1dbde5bc93202874c412011739589dfc8)"}
```
**Metrics**
N/A

**Operating System**
GCP Ubuntu 22.04 (latest stock image)

**Additional context**
_dub_rado_ pointed me to the workaround, starting the node with pruning enabled, and state-sync disabled in config. He has advised me to let this run to completion, then restart the node with both pruning and state-sync enabled.

In the first stage now, and it has started cleaning up:
```
May 22 20:25:49 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:49.557] <C Chain> github.com/ava-labs/coreth/eth/backend.go:441: Starting offline pruning dataDir=/opt/avalanchego/offline-pruning bloomFilterSize=512
May 22 20:25:49 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:49.558] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/journal.go:106: Resuming previous snapshot wipe
May 22 20:25:49 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:49.558] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/snapshot.go:354: Waiting for snapshot generation root=6923f6..bcd536
May 22 20:25:49 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:49.558] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/generate.go:125: Wiper running, state snapshotting paused accounts=0 slots=0 storage=0.00B elapsed="33.681µs"
May 22 20:25:57 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:57.620] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=460,000 elapsed=8.077s
May 22 20:25:57 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:25:57.733] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=450,000 elapsed=8.175s
May 22 20:26:05 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:05.731] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=920,000 elapsed=16.187s
May 22 20:26:05 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:05.849] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=890,000 elapsed=16.290s
May 22 20:26:13 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:13.778] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=1,710,000 elapsed=24.234s
May 22 20:26:13 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:13.951] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=1,710,000 elapsed=24.392s
May 22 20:26:21 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:21.832] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=2,630,000 elapsed=32.288s
May 22 20:26:22 avalanche-mainnet-vm avalanchego[143154]: INFO [05-22|20:26:22.017] <C Chain> github.com/ava-labs/coreth/core/state/snapshot/wipe.go:123: Deleting state snapshot leftovers kind=accounts wiped=2,630,000 elapsed=32.458s
```

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

**Comment by mattmartinez** [comment]
Having the same issue after upgrading a fully sync'd server from 1.10.1 ->. 1.10.5

[07-26|17:28:11.116] FATAL chains/manager.go:338 error creating required chain {"subnetID": "11111111111111111111111111111111LpoYY", "chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "vmID": "mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6", "error": "error while creating new snowman vm node has operated with pruning disabled, shutting down to prevent missing tries"}

**Comment by mattmartinez** [comment]
I wasn't able to start it back up after the upgrade until i made these changes to the C config:

```
  "allow-missing-tries": true,
  "offline-pruning-enabled": true,
  "offline-pruning-data-directory": "/folder/path/to/pruning"
```
